baseURL = "https://cshubhamrao.dev"
languageCode = "en"
defaultContentLanguage = "en"
title = "Shubham Rao"
theme = "hugo-coder"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "yourdiscussshortname"

[params]
    author = "Shubham Rao"
    description = "Shubham Rao's personal website"
    keywords = "blog,developer,personal"
    info = "AI/ML/DL Engineer"
    avatarurl = "logo.jpg"
    favicon_32 = "favicon-32x32.png"
    favicon_16 = "favicon-16x16.png"
    #gravatar = "john.doe@example.com"
    footercontent = "Computer Science undergrad looking for a career as a Machine Learning and Artificial Intelligence Engineer. Experienced ML practitioner with a strong background in designing, developing and deploying ML applications. Experienced in a variety of Computer Science and Software Development Skills."

    dateformat = "January 2, 2006"

    hideFooter = false
    hideCredits = false
    hideCopyright = false
    since = 2020

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = false

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

# # If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
#     siteID = "ABCDE"
#     # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
#     serverURL = "analytics.example.com"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/cshubhamrao/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/cshubhamrao/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/cshubhamrao/"
[[params.social]]
    name = "Email"
    icon = "fab fa-facebook"
    weight = 4
    url = "https://www.facebook.com/cshubhamrao"
[[params.social]]
    name = "Email"
    icon = "fas fa-envelope"
    weight = 5
    url = "mailto:contact@cshubhamrao.dev"


[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            # [[languages.en.menu.main]]
            # name = "Blog"
            # weight = 2
            # url = "posts/"

            # [[languages.en.menu.main]]
            # name = "Projects"
            # weight = 3
            # url = "projects/"

            # [[languages.en.menu.main]]
            # name = "Contact me"
            # weight = 5
            # url = "contact/"

